// Comuni della Città metropolitana di Roma Capitale
export const comuniRomaMetropolitana = [
  'Roma',
  'Affile',
  'Agosta',
  'Albano Laziale',
  'Allumiere',
  'Anguillara Sabazia',
  'Anticoli Corrado',
  'Anzio',
  'Arcinazzo Romano',
  'Ardea',
  'Ariccia',
  'Arsoli',
  'Artena',
  'Bellegra',
  'Bracciano',
  'Camerata Nuova',
  'Campagnano di Roma',
  'Canale Monterano',
  'Canterano',
  'Capena',
  'Capranica Prenestina',
  'Carpineto Romano',
  'Casape',
  'Case',
  'Castel Gandolfo',
  'Castel Madama',
  'Castel San Pietro Romano',
  'Castelnuovo di Porto',
  'Cave',
  'Cerreto Laziale',
  'Cervara di Roma',
  'Cerveteri',
  'Ciampino',
  'Ciciliano',
  'Cineto Romano',
  'Civitavecchia',
  'Civitella San Paolo',
  'Colleferro',
  'Colonna',
  'Fiano Romano',
  'Filacciano',
  'Formello',
  'Frascati',
  'Gallicano nel Lazio',
  'Gavignano',
  'Genazzano',
  'Genzano di Roma',
  'Gerano',
  'Gorga',
  'Grottaferrata',
  'Guidonia Montecelio',
  'Jenne',
  'Labico',
  'Lanuvio',
  'Lariano',
  'Licenza',
  'Magliano Romano',
  'Mandela',
  'Manziana',
  'Marano Equo',
  'Marcellina',
  'Marino',
  'Mazzano Romano',
  'Mentana',
  'Monte Compatri',
  'Monte Porzio Catone',
  'Monteflavio',
  'Montelanico',
  'Montelibretti',
  'Monterotondo',
  'Montorio Romano',
  'Moricone',
  'Morlupo',
  'Nazzano',
  'Nemi',
  'Nerola',
  'Nettuno',
  'Olevano Romano',
  'Palestrina',
  'Palombara Sabina',
  'Percile',
  'Pisoniano',
  'Poli',
  'Pomezia',
  'Ponzano Romano',
  'Riano',
  'Rignano Flaminio',
  'Riofreddo',
  'Rocca Canterano',
  'Rocca di Cave',
  'Rocca di Papa',
  'Rocca Priora',
  'Rocca Santo Stefano',
  'Roccagiovine',
  'Roiate',
  'Roviano',
  'Sacrofano',
  'Sambuci',
  'San Cesareo',
  'San Gregorio da Sassola',
  'San Polo dei Cavalieri',
  'San Vito Romano',
  'Santa Marinella',
  'Sant\'Angelo Romano',
  'Sant\'Oreste',
  'Saracinesco',
  'Segni',
  'Subiaco',
  'Tivoli',
  'Tolfa',
  'Torrita Tiberina',
  'Trevignano Romano',
  'Vallepietra',
  'Vallinfreda',
  'Valmontone',
  'Velletri',
  'Vicovaro',
  'Vivaro Romano',
  'Zagarolo',
];

// Comuni italiani più comuni per luogo di nascita (se nato fuori dalla Città metropolitana)
export const altriComuniComuni = [
  'Milano',
  'Napoli',
  'Torino',
  'Palermo',
  'Genova',
  'Bologna',
  'Firenze',
  'Bari',
  'Catania',
  'Venezia',
  'Verona',
  'Messina',
  'Padova',
  'Trieste',
  'Brescia',
  'Parma',
  'Taranto',
  'Prato',
  'Modena',
  'Reggio Calabria',
  'Reggio Emilia',
  'Perugia',
  'Ravenna',
  'Livorno',
  'Cagliari',
  'Foggia',
  'Rimini',
  'Salerno',
  'Ferrara',
  'Sassari',
  'Latina',
  'Giugliano in Campania',
  'Monza',
  'Siracusa',
  'Pescara',
  'Bergamo',
  'Forlì',
  'Trento',
  'Vicenza',
  'Terni',
  'Bolzano',
  'Novara',
  'Piacenza',
  'Ancona',
  'Andria',
  'Arezzo',
  'Udine',
  'Cesena',
  'Lecce',
  'Pesaro',
];

// Combina tutti i comuni per il luogo di nascita
export const tuttiComuni = [
  ...comuniRomaMetropolitana,
  ...altriComuniComuni,
].sort();
